services:
  - type: web
    name: d-asap-tools
    runtime: static
    buildCommand: "echo no build step needed"
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: "public, max-age=0, must-revalidate"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
